meta_product_name: "ArtCartel"
meta_title: "ArtCartel - Discover. Play. Master."
meta_description: "The art history game that will train your eye."
meta_image: "metaIMG.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
